openapi: 3.0.3
info:
  title: Employee API to know the staff and in which work department
  description: |-
    A simple Enterprise API to allows two operations
    - get a list of employees
    - create a new employee
    - get an information about the employee
    - edit an employee
    - delete an employee
  version: 1.0- SNAPSHOT
servers:
  - url: https://testenvironment.org/api/v1
  - url: https://prodenvironment.org/api/v1
tags:
  - name: employee
    description: Employee management

paths:
  /employee:
    get:
      tags:
        - employee
      summary: list of employees
      description: Retrieve the list of all employees
      operationId: getEmployees
      responses:
        200:
          description: List of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmployeesResponse'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /employee/new:
    post:
      tags:
        - employee
      summary: New employee
      description: Create a new employee
      operationId: createEmployee
      requestBody:
        description: name, firstname, service and floor
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEmployeeRequest'
      responses:
        201:
          description: Employee created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeResponse'
        404:
          $ref: '#/components/responses/404'
        405:
          $ref: '#/components/responses/405'
        500:
          $ref: '#/components/responses/500'

  /employee/{id}:
    get:
      tags:
        - employee
      summary: Get employee by ID
      description: Retrieve employee details by ID
      operationId: getEmployeeById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Employee found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeResponse'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

    delete:
      tags:
        - employee
      summary: Delete employee
      description: Delete employee
      operationId: deleteEmployee
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          $ref: '#/components/responses/204'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /employee/edit/{id}:
    put:
      tags:
        - employee
      summary: Update employee
      description: Update an existing employee
      operationId: updateEmployee
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmployeeRequest'
      responses:
        200:
          description: Employee updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeResponse'
        404:
          $ref: '#/components/responses/404'
        405:
          $ref: '#/components/responses/405'
        500:
          $ref: '#/components/responses/500'

components:
  schemas:
    EmployeesResponse:
      type: object
      properties:
        name:
          type: string
        firstname:
          type: string

    EmployeeResponse:
      type: object
      properties:
        name:
          type: string
        firstname:
          type: string
        service:
          type: string
        floor:
          type: integer
          format: int32
        address:
          $ref: '#/components/schemas/Address'

    EmployeeWithoutAddressResponse:
      type: object
      properties:
        name:
          type: string
        firstname:
          type: string
        service:
          type: string
        floor:
          type: integer
          format: int32

    CreateEmployeeRequest:
      type: object
      required:
        - name
        - firstname
      properties:
        name:
          type: string
        firstname:
          type: string
        service:
          type: string
        floor:
          type: integer
          format: int32
        address:
          $ref: '#/components/schemas/Address'

    UpdateEmployeeRequest:
      type: object
      properties:
        name:
          type: string
        firstname:
          type: string
        service:
          type: string
        floor:
          type: integer
          format: int32

    Address:
      type: object
      properties:
        street:
          type: string
        zipcode:
          type: integer
          format: int32
        city:
          type: string

  responses:
    204:
      description: Employee deleted successfully

    404:
      description: Object not found
      content:
        application/problem+json:
          schema:
            $ref: '../resources/problem.yaml#/components/schemas/Problem'

    405:
      description: Invalid input
      content:
        application/problem+json:
          schema:
            $ref: '../resources/problem.yaml#/components/schemas/Problem'

    500:
      description: Error Server
      content:
        application/problem+json:
          schema:
            $ref: '../resources/problem.yaml#/components/schemas/Problem'
